DROP TABLE IF EXISTS dishes CASCADE ;
DROP TABLE IF EXISTS lunches CASCADE ;
DROP TABLE IF EXISTS restaurants CASCADE ;
DROP TABLE IF EXISTS votes CASCADE ;
DROP TABLE IF EXISTS users CASCADE ;
DROP TABLE IF EXISTS roles CASCADE ;

CREATE TABLE restaurants(
  id SERIAL PRIMARY KEY,
  name VARCHAR(20)
);

CREATE TABLE dishes(
id SERIAL PRIMARY KEY,
name VARCHAR(20) NOT NULL,
description VARCHAR(100),
price INT NOT NULL
);

CREATE TABLE lunches(
  id SERIAL PRIMARY KEY,
  date DATE,
  dishId INT REFERENCES dishes(id) ON DELETE CASCADE ,
  restId INT REFERENCES restaurants(id) ON DELETE CASCADE
);



CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  email VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL,
  registered DATE
);

CREATE TABLE roles(
  id SERIAL PRIMARY KEY,
  userid INT REFERENCES users(id) ON DELETE CASCADE,
  role VARCHAR
);

CREATE TABLE votes(
  id SERIAL PRIMARY KEY,
  userId INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  restId INT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE
)